allowBuilds:
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

minimumReleaseAge: 10080
trustPolicy: no-downgrade
blockExoticSubdeps: true
